### PR TITLE
Feature/minor config changes

### PR DESCRIPTION
**Pull request by rubenchazarra**
This PR includes the following features: 
- [x] Include dataset ID argument to output file names
- [x] Include lines in main.nf to ensure that nested workflow is ran in its develop branch. 
- [x] Include matrix type in confing

**DOUBT:**
STILL don't understand why commits that where already merged in develop appear again here!

### CODE REVIEW

**Comment by pinin4fjords** [comment]
@rubenchazarra - you must not have pulled the latest changes to develop before you created this branch off develop. You should double-check the changed files to make sure the changes are what you intend, and when you squash merge, please make sure that you tidy up the commit message to remove all the commits that were part of the newest develop you've merged in.

@a-solovyev12 - can you comment on whether you think e.g. the matrix type handling looks good here?

**Comment by pinin4fjords** [comment]
@rubenchazarra - how do you see your matrix fetching step working here, if multiple types are required by the child workflow? Correct me if I'm wrong, but I only see provision for fetching and downloading the one matrix type. You're not actually using the method-wise matrix type settings you're adding here, are you?

**Review by a-solovyev12 — APPROVED** [review]
@rubenchazarra looks good to me. Please open a new PR for the data download feature

**Comment by a-solovyev12** [comment]
@pinin4fjords we've discussed this and agreed on a similar method to what I have in the training workflow. This feature should be added in a new PR I reckon.

**Comment by pinin4fjords** [comment]
@a-solovyev12 Ahh- so the matrix type stuff here is a bit of a red herring?

**Comment by a-solovyev12** [comment]
@pinin4fjords Ah I see now, sorry. I think this point should be removed @rubenchazarra.

**Comment by rubenchazarra** [comment]
@pinin4fjords you're right, I was going to add the differential matrix download in this PR but my plan is to first merge this PR, and then open a new PR for that issue. This PR only includes some minor changes done to the config and main. This is basically, so that I can keep running things on develop, while I start making changes in a new branch. 
Regarding cleaning the commit history before merging, this is sth I am not sure about how to do.  Could you point me out how to do?

**Comment by rubenchazarra** [comment]
Ok @a-solovyev12  I will remove the matrix type specifications in config, to make things more clear

**Comment by pinin4fjords** [comment]
@rubenchazarra - nothing complicated. When you go to squash merge GitHub will pop up a list of all the commits here, which will be added as a message on the new commit. Just make sure you edit that message to remove the commits that were already there.

**Pull request merged**
